export const response = {
    content: [
        {
            id: 1616,
            tailNumber: 'JACKT1',
            modelName: 'Citation CJ2',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 301,
            tailNumber: 'N100EK',
            modelName: 'Gulfstream G200',
            categoryName: 'Super Mid Size Jet',
            categoryId: 6,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 0
        },
        {
            id: 73,
            tailNumber: 'N1122K',
            modelName: 'Citation Excel',
            categoryName: 'Mid Size Jet',
            categoryId: 5,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceApproved: false,
            deleted: false,
            serviceClassId: 1
        },
        {
            id: 74,
            tailNumber: 'N125TH',
            modelName: 'Citation X',
            categoryName: 'Super Mid Size Jet',
            categoryId: 6,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceExpirationDate: '2021-11-30',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        },
        {
            id: 75,
            tailNumber: 'N127SJ',
            modelName: 'Beechjet 400',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceApproved: false,
            deleted: false,
            serviceClassId: 0
        }, {
            id: 1598,
            tailNumber: 'N157PB',
            modelName: 'Learjet 45',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceExpirationDate: '2020-07-15',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 302,
            tailNumber: 'N173KR',
            modelName: 'Learjet 60',
            categoryName: 'Mid Size Jet',
            categoryId: 5,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceExpirationDate: '2021-11-05',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 76,
            tailNumber: 'N175MX',
            modelName: 'Learjet 75',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceExpirationDate: '2020-07-15',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 77,
            tailNumber: 'N178BR',
            modelName: 'Citation Excel',
            categoryName: 'Mid Size Jet',
            categoryId: 5,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceExpirationDate: '2020-07-15',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 78,
            tailNumber: 'N180YA',
            modelName: 'Citation CJ2',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 4,
            insuranceApproved: false,
            deleted: false,
            serviceClassId: 0
        }, {
            id: 79,
            tailNumber: 'N188WS',
            modelName: 'Citation Excel',
            categoryName: 'Mid Size Jet',
            categoryId: 5,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceApproved: false,
            deleted: false,
            serviceClassId: 0
        }, {
            id: 80,
            tailNumber: 'N1AZ',
            modelName: 'Gulfstream IV-SP',
            categoryName: 'Heavy Jet',
            categoryId: 7,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 12,
            insuranceExpirationDate: '2020-07-15',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 81,
            tailNumber: 'N218PH',
            modelName: 'Falcon 2000',
            categoryName: 'Heavy Jet',
            categoryId: 7,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceApproved: false,
            deleted: false,
            serviceClassId: 0
        }, {
            id: 275,
            tailNumber: 'N226MY',
            modelName: 'Challenger 604',
            categoryName: 'Heavy Jet',
            categoryId: 7,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 8,
            insuranceExpirationDate: '2019-11-28',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }, {
            id: 82,
            tailNumber: 'N226WC',
            modelName: 'Nextant 400XTi',
            categoryName: 'Light Jet',
            categoryId: 4,
            operatorId: 'bf112259-d7ef-48f4-aed5-ab2c579bb5e1',
            offFleetOperatorIds: [],
            maxPax: 6,
            insuranceExpirationDate: '2019-11-28',
            insuranceApproved: true,
            deleted: false,
            serviceClassId: 1
        }
    ],
    pageable: {
        sort: {
            sorted: true,
            unsorted: false,
            empty: false
        },
        offset: 0,
        pageSize: 15,
        pageNumber: 0,
        unpaged: false,
        paged: true
    },
    totalPages: 6,
    totalElements: 81,
    last: false,
    first: true,
    sort: {
        sorted: true,
        unsorted: false,
        empty: false
    },
    size: 15,
    number: 0,
    numberOfElements: 15,
    empty: false
};
